# default profile settings
spring:
  profiles:
    active: local

# Swagger
springdoc:
  swagger-ui:
    path: /swagger
    display-request-duration: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  cors:
    enabled: true

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sajang_db
    username: sajang_user
    password: sajang_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
